[package]
name = "gin-tonic-core"
version = "0.4.2"
edition = "2021"
repository = "https://github.com/cemoktra/gin-tonic/"
description = "core functions for gin-tonic"
license = "MIT"
readme = "../README.md"
keywords = ["grpc", "protobuf", "tonic"]

[features]
default = []
uuid_string = ["dep:uuid"]
uuid_bytes = ["dep:uuid"]

[dependencies]
integer-encoding = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, optional = true }

[lints]
workspace = true
