[workspace]

[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
gin-tonic = { path = "../../gin", version = "0.4.0", features = ["uuid_bytes"] }
tonic = "0.11.0"
uuid = "1.8.0"

[build-dependencies]
gin-tonic = { path = "../../gin", version = "0.4.0", features = ["uuid_bytes"] }

